### ISSUE TITLE
The load time for web pages that have a Cotton component increases with every page load

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#83]
Since starting to evaluate Cotton I've noticed that page load times increase with every page load.  My home page has one component (with about 10 instances).  I used Chrome's dev tools to time successive page loads (I forced reloading with F5):

79ms
107ms
169ms
200ms
246ms
284ms
.
.
.
after 20 more loads the load time is up to 1.21 seconds and still increasing with each load.

If I disable Cotton (by removing the loaders in settings.py OPTIONS) then the load time drops to around 30ms where I would expect it to be.

I have also replicated this issue with a minimal app, though the load time increases much more slower (but still does increase).

**Comment by wrabit** [comment]
@ra-dave I've not been able to replicate this my side, can you share your settings.py, view and component?

**Comment by wrabit** [comment]
@ra-dave looking into this further I have noticed something whilst in dev (DEBUG=True) that could be causing the issue. I will look into it and post back when I have a solution.

**Comment by ra-dave** [comment]
Ok.  Let me know if you still want the minimal test app and I can upload it.

**Comment by wrabit** [comment]
@ra-dave this has been addressed in #84 and released as v0.9.27, could you try it out and we can keep tabs on it here..

**Comment by ra-dave** [comment]
Well the problem has gone away with my minimal test project but unfortunately the problem remains with my main project.  I even rebuilt my venv and re-installed all packages to make sure everything is updated.

As before, page load time continually increases with each refresh.  Problem goes away if I remove the cotton loader from settings.py.  Any thoughts on how I should proceed here?  Maybe do some profiling to see where all the time is being spent?

**Comment by ra-dave** [comment]
Ok, so I see your loaders in your settings.py has a cached.Loader:

            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django_cotton.cotton_loader.Loader",
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                )
            ],

I changed my settings.py to match that and the problem went away!  Does that make sense?  I wonder why that change was not necessary for my test project?

**Comment by wrabit** [comment]
Yes the caching approach needs a review (as mentioned in the readme) and it will be the first item I tend to.

**Comment by ra-dave** [comment]
@wrabit I understand you're working on improving the caching but my current problem is when I make a change to a component it's not getting rebuilt until I restart the web server.  Is there a way I can force a cache clear or some other workaround for now?

**Comment by wrabit** [comment]
@ra-dave I pushed out the release in a bit of a rush. It's now been reverted until I can address it properly.

**Comment by randallmlough** [comment]
Just wanted to chime in and say we are also experiencing this problem. We've had to temporary disable cotton until this problem gets resolved. Thanks for your work on this.

**Comment by wrabit** [comment]
@ra-dave @randallmlough just to let you know a new release is out which simplifies some of the caching strategies that existed. It should now behave better - please check it out. Also - cotton will now attempt to auto-configure your settings, managing the `loaders` and `builtins` on boot. Along with simplicity of setup, one upside is that you needn't specify `DIRS` and can leave `APP_DIRS` too. 

- https://github.com/wrabit/django-cotton/releases/tag/v0.9.29

**Comment by ra-dave** [comment]
I can confirm that my issue with the components not being rebuilt after a change has been fixed.  And page load times now look good.  Thanks for the quick fixes!  This library has great potential.
